### PR TITLE
add TDD, add some group, remove dead link

### PR DESCRIPTION
**Pull request by codenoid**
+ talk about test driven development, &etc

### CODE REVIEW

**Comment by codenoid** [comment]
gimana mas @hendisantika kalo dibuat ci buat validasi alphabetical order

**Comment by codenoid** [comment]
fix issue like #26

**Comment by codenoid** [comment]
@mardinw 😕  , `suggested changes`, change what ? :/

**Comment by mardinw** [comment]
@codenoid 
 Haha... ketahuan saya jarang pakai PR

**Comment by codenoid** [comment]
oh iya om @mardinw , #28 mohon di close, soal nya sudah di perbaiki di #27 , 😸  👍

**Comment by codenoid** [comment]
tolong travis nya om :D, hehe https://travis-ci.org/hendisantika/List-All-Programming-Telegram-Group

**Pull request merged**
