### PR TITLE
add HackTheBox Indonesia

### PR DESCRIPTION
**Pull request by rizkytegar**
Menambahkan forum HackTheBox Indonesia. Forum terbuka untuk belajar Cyber Security, Pentesting, Ethical Hacking, dan CTF dengan platform HackTheBox.

### CODE REVIEW

**Comment by rizkytegar** [comment]
excusme, @hendisantika. this repo available for Hacktoberfest ?

**Comment by hendisantika** [comment]
Hi @rizkytegar , Yes, it is.

**Comment by hendisantika** [comment]
It's already there. You can check on topics

**Comment by hendisantika** [comment]
Hacktoberfest tag is for Project not a PR. PR will be included on that project as Hacktoberfest donation.

**Pull request merged**
