### PR TITLE
Add group

### PR DESCRIPTION
**Pull request by hamidreza01**
In the mentioned groups, things like open source are discussed

### CODE REVIEW

**Comment by hendisantika** [comment]
Itu grup apa?

Yg jelas dong commit nya

**Comment by hamidreza01** [comment]
There is a discussion group of open source programmers

**Comment by hamidreza01** [comment]
> Itu grup apa?
> 
> Yg jelas dong commit nya

There is a discussion group of open source programmers

**Comment by hendisantika** [comment]
Harus public link/group not a private group

**Comment by hamidreza01** [comment]
> Harus public link/group not a private group

I don't understand, this is a public group, you can see its username

**Comment by hamidreza01** [comment]
If you mean that I must put the private link, then the rest of the contributors have also put the public link, this is really illogical, I don't understand!

**Comment by hendisantika** [comment]
The grup should be public link not private group with private link.

**Comment by hamidreza01** [comment]
Well, no problem, I don't understand, that link is already public

**Comment by hamidreza01** [comment]
:/

**Comment by hamidreza01** [comment]
That was really stupid, the links are already public

**Pull request closed without merging**
